<a href="https://colab.research.google.com/github/dwelle511/2026BDA/blob/main/BDA_Day11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print(100)

100

In [117]:
#메모리크기, 열 정보, 데이터프레임, 레인지
!git clone https://github.com/ai7dnn/data.git
import pandas as pd

exam = pd.read_csv('data/exam.csv')
exam.head()

fatal: destination path 'data' already exists and is not an empty directory.

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [3]:
exam.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       20 non-null     int64
 1   nclass   20 non-null     int64
 2   math     20 non-null     int64
 3   english  20 non-null     int64
 4   science  20 non-null     int64
dtypes: int64(5)
memory usage: 932.0 bytes

In [118]:
exam.describe()

             id     nclass       math    english    science
count  20.00000  20.000000  20.000000  20.000000  20.000000
mean   10.50000   3.000000  57.450000  84.900000  59.450000
std     5.91608   1.450953  20.299015  12.875517  25.292968
min     1.00000   1.000000  20.000000  56.000000  12.000000
25%     5.75000   2.000000  45.750000  78.000000  45.000000
50%    10.50000   3.000000  54.000000  86.500000  62.500000
75%    15.25000   4.000000  75.750000  98.000000  78.000000
max    20.00000   5.000000  90.000000  98.000000  98.000000

In [119]:
!pip install koreanize_matplotlib
import koreanize_matplotlib
# 그림 선명하게
%config InlineBackend.figure_format = 'retina'

Collecting koreanize_matplotlib
  Downloading koreanize_matplotlib-0.1.1-py3-none-any.whl.metadata (992 bytes)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from koreanize_matplotlib) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->koreanize_matplotlib) (1.17.0)
Downloading koreanize_matplotlib-0.1.1-py3-none-any.whl (7.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 61.9 MB/s eta 0:00:00
Installing collected packages: koreanize_matplotlib
Successfully installed koreanize_matplotlib-0.1.1

In [120]:
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [5, 3]

In [121]:
exam.describe()[["id","math"]]

             id       math
count  20.00000  20.000000
mean   10.50000  57.450000
std     5.91608  20.299015
min     1.00000  20.000000
25%     5.75000  45.750000
50%    10.50000  54.000000
75%    15.25000  75.750000
max    20.00000  90.000000

In [123]:
from IPython.display import display_html
import inspect
import ast

def display_side_by_side(*dfs):
    titles = []

    try:
        caller_frame = inspect.currentframe().f_back
        call_line = inspect.getframeinfo(caller_frame).code_context[0].strip()

        tree = ast.parse(call_line)
        call = tree.body[0].value

        if isinstance(call, ast.Call):
            for arg in call.args:
                titles.append(ast.get_source_segment(call_line, arg))
    except:
        titles = [''] * len(dfs)

    if len(titles) < len(dfs):
        titles += [''] * (len(dfs) - len(titles))

    html_str = ''
    for df, title in zip(dfs, titles):
        html_str += f"""
        <div style="display:inline-block; vertical-align:top; margin-right:20px; text-align:center;">
            <div style="font-weight:bold; font-size:13px; margin-bottom:8px; text-align:center;">
                {title}
            </div>
            <div style="display:flex; justify-content:center;">
                {df.to_html()}
            </div>
        </div>
        """

    display_html(html_str, raw=True)

In [124]:
display_side_by_side(exam.head(),exam.tail())

,id,nclass,math,english,science
0,1,1,50,98,50
1,2,1,60,97,60
2,3,1,45,86,78
3,4,1,30,98,58
4,5,2,25,80,65
,id,nclass,math,english,science
15,16,4,58,98,65
16,17,5,65,68,98
17,18,5,80,78,90
18,19,5,89,68,87
19,20,5,78,83,58

In [125]:
#반이 5개 라는거죠
exam.nclass.unique()

array([1, 2, 3, 4, 5])

In [126]:
#agg()함수 : 하나 이상의 집계 함수를 axis따라 적용하는 , 집계함수
# sum,maen,std,min,max,median,first,last,nunique
exam.agg("median")

id         10.5
nclass      3.0
math       54.0
english    86.5
science    62.5
dtype: float64

In [128]:
exam.nunique("mean")
#이런 문법은 없음

ValueError: No axis named mean for object type DataFrame

In [129]:
from IPython.display import display_html
import inspect
import ast

def display_series_side_by_side(*args):
    """여러 Series를 옆으로 나란히 표시하고,
    호출 시 사용한 표현식을 제목으로 위에 출력한다.
    """
    titles = []

    try:
        caller_frame = inspect.currentframe().f_back
        call_line = inspect.getframeinfo(caller_frame).code_context[0].strip()

        tree = ast.parse(call_line)
        call = tree.body[0].value

        if isinstance(call, ast.Call):
            for arg in call.args:
                titles.append(ast.get_source_segment(call_line, arg))
    except:
        titles = [''] * len(args)

    if len(titles) < len(args):
        titles += [''] * (len(args) - len(titles))

    html_str = ''
    for s, title in zip(args, titles):
        table_html = s.to_frame().to_html()

        html_str += f"""
        <div style="display:inline-block; vertical-align:top; margin-right:20px; text-align:center;">
            <div style="font-weight:bold; font-size:13px; margin-bottom:8px; text-align:center;">
                {title}
            </div>
            <div style="display:flex; justify-content:center;">
                {table_html}
            </div>
        </div>
        """

    display_html(html_str, raw=True)

In [25]:
# 둘이 같은 결과이다, 기억해보자
display_series_side_by_side(exam.mean(), exam.agg("mean"))

,0
id,10.50
nclass,3.00
math,57.45
english,84.90
science,59.45
,0
id,10.50
nclass,3.00
math,57.45
english,84.90
science,59.45

In [26]:
#의미는 무엇인가?
exam.mean(axis=1)

0     40.0
1     44.0
2     42.6
3     38.2
4     35.4
5     49.0
6     44.8
7     40.6
8     29.0
9     41.2
10    41.8
11    35.4
12    45.2
13    33.0
14    45.6
15    48.2
16    50.6
17    54.2
18    53.6
19    48.8
dtype: float64

In [134]:
exam.agg("corr")

               id    nclass      math   english   science
id       1.000000  0.981023  0.490638 -0.476757  0.205939
nclass   0.981023  1.000000  0.421726 -0.456398  0.230898
math     0.490638  0.421726  1.000000 -0.540915  0.272162
english -0.476757 -0.456398 -0.540915  1.000000 -0.407448
science  0.205939  0.230898  0.272162 -0.407448  1.000000

In [135]:
#to_frame() 뭐지 =>
display_side_by_side(exam.agg("mean").to_frame(),exam.agg(["mean","max","min","median"]))

In [137]:
display_side_by_side(exam.agg(["count","mean","std","min","median","max"]),exam.describe())

,id,nclass,math,english,science
count,20.00000,20.000000,20.000000,20.000000,20.000000
mean,10.50000,3.000000,57.450000,84.900000,59.450000
std,5.91608,1.450953,20.299015,12.875517,25.292968
min,1.00000,1.000000,20.000000,56.000000,12.000000
median,10.50000,3.000000,54.000000,86.500000,62.500000
max,20.00000,5.000000,90.000000,98.000000,98.000000
,id,nclass,math,english,science
count,20.00000,20.000000,20.000000,20.000000,20.000000
mean,10.50000,3.000000,57.450000,84.900000,59.450000
std,5.91608,1.450953,20.299015,12.875517,25.292968
min,1.00000,1.000000,20.000000,56.000000,12.000000
25%,5.75000,2.000000,45.750000,78.000000,45.000000
50%,10.50000,3.000000,54.000000,86.500000,62.500000
75%,15.25000,4.000000,75.750000,98.000000,78.000000
max,20.00000,5.000000,90.000000,98.000000,98.000000

In [32]:
#
exam.agg(mean_math이름짓기=('math','mean'))

                math
mean_math이름짓기  57.45

In [33]:
#영어의 최고점을 출력
#단점 missing value 나옴
exam.agg(영어_최고점=('math','mean'),영어최고=('english','max'))

         math  english
영어_최고점  57.45      NaN
영어최고      NaN     98.0

In [36]:
# 단점을 보완한
import pandas as pd
pd.DataFrame([
    {'지표':'수학지표','값':exam['math'].mean()},
    {'지표':'영어최고','값':exam['english'].max()},
    {'지표':'과학최저','값':exam['science'].min()}
]).set_index('지표')

#set_index() : ()안의 값을 데이터프레임 맨 왼쪽에 있는 index으로 사용한다

          값
지표
수학지표  57.45
영어최고  98.00
과학최저  12.00

In [37]:
import numpy as np
df=pd.DataFrame([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [np.nan,np.nan,10]],
                 columns=['A','B','C'])
df

     A    B   C
0  1.0  2.0   3
1  4.0  5.0   6
2  7.0  8.0   9
3  NaN  NaN  10

In [40]:
df.agg(['count','sum','mean'],axis=1)
#axis=0 과 axis=1은 역함수 .T생각하면되나욤

   count   sum  mean
0    3.0   6.0   2.0
1    3.0  15.0   5.0
2    3.0  24.0   8.0
3    1.0  10.0  10.0

In [141]:
#,axis='index' 없애도 동일한데
df.agg(['count','sum','mean','min','median','max'],axis='index')

           A     B     C
count    3.0   3.0   4.0
sum     12.0  15.0  28.0
mean     4.0   5.0   7.0
min      1.0   2.0   3.0
median   4.0   5.0   7.5
max      7.0   8.0  10.0

In [145]:
df

     A    B   C
0  1.0  2.0   3
1  4.0  5.0   6
2  7.0  8.0   9
3  NaN  NaN  10

In [147]:
#.t 되어있다= axis=1 이거랑 axis='columns'동일
df.agg(['count', 'sum', 'mean', 'min', 'median', 'max'],axis=1)

   count   sum  mean   min  median   max
0    3.0   6.0   2.0   1.0     2.0   3.0
1    3.0  15.0   5.0   4.0     5.0   6.0
2    3.0  24.0   8.0   7.0     8.0   9.0
3    1.0  10.0  10.0  10.0    10.0  10.0

In [150]:
df.agg(['count', 'sum', 'mean', 'min', 'median', 'max'],axis='columns')

   count   sum  mean   min  median   max
0    3.0   6.0   2.0   1.0     2.0   3.0
1    3.0  15.0   5.0   4.0     5.0   6.0
2    3.0  24.0   8.0   7.0     8.0   9.0
3    1.0  10.0  10.0  10.0    10.0  10.0

### 집단별 집계함수 사용패턴
### groupby()

In [41]:
exam

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [155]:
exam.describe()

             id     nclass       math    english    science
count  20.00000  20.000000  20.000000  20.000000  20.000000
mean   10.50000   3.000000  57.450000  84.900000  59.450000
std     5.91608   1.450953  20.299015  12.875517  25.292968
min     1.00000   1.000000  20.000000  56.000000  12.000000
25%     5.75000   2.000000  45.750000  78.000000  45.000000
50%    10.50000   3.000000  54.000000  86.500000  62.500000
75%    15.25000   4.000000  75.750000  98.000000  78.000000
max    20.00000   5.000000  90.000000  98.000000  98.000000

In [156]:
#반별을 인덱스로 한 .agg(열 이름=('보고싶은 값의 열','집계함수'))
#
exam.groupby('nclass').agg(mean_math=('science','mean'))

        mean_math
nclass
1           61.50
2           58.25
3           39.25
4           55.00
5           83.25

In [44]:
exam.groupby('nclass').agg(max_math=('math','max'))

        max_math
nclass
1             60
2             90
3             65
4             75
5             89

In [157]:
#groupby(열) : 열을 인텍스로 사용하여 평균은 열로 보여준다
exam.groupby('nclass').mean()
#특정 열만 보이거나 df[,1]만 제거하고 싶은데 방법은?

          id   math  english  science
nclass
1        2.5  46.25    94.75    61.50
2        6.5  61.25    84.25    58.25
3       10.5  45.00    86.50    39.25
4       14.5  56.75    84.75    55.00
5       18.5  78.00    74.25    83.25

In [46]:
exam.groupby('nclass').mean()[["math"]]

         math
nclass
1       46.25
2       61.25
3       45.00
4       56.75
5       78.00

In [47]:
exam.groupby('nclass').mean()[["math","english","science"]]

         math  english  science
nclass
1       46.25    94.75    61.50
2       61.25    84.25    58.25
3       45.00    86.50    39.25
4       56.75    84.75    55.00
5       78.00    74.25    83.25

In [158]:
exam.groupby('nclass').min()

        id  math  english  science
nclass
1        1    30       86       50
2        5    25       78       25
3        9    20       65       15
4       13    46       56       12
5       17    65       68       58

In [48]:
exam.groupby('nclass').agg("mean")

          id   math  english  science
nclass
1        2.5  46.25    94.75    61.50
2        6.5  61.25    84.25    58.25
3       10.5  45.00    86.50    39.25
4       14.5  56.75    84.75    55.00
5       18.5  78.00    74.25    83.25

In [159]:
# 열이 여러개 있는거 : MultiIndex()
exam.groupby('nclass').agg(["mean","median","max"])

          id              math            english            science         \
        mean median max   mean median max    mean median max    mean median
nclass
1        2.5    2.5   4  46.25   47.5  60   94.75   97.5  98   61.50   59.0
2        6.5    6.5   8  61.25   65.0  90   84.25   84.5  90   58.25   55.0
3       10.5   10.5  12  45.00   47.5  65   86.50   91.5  98   39.25   38.5
4       14.5   14.5  16  56.75   53.0  75   84.75   92.5  98   55.00   65.0
5       18.5   18.5  20  78.00   79.0  89   74.25   73.0  83   83.25   88.5


       max
nclass
1       78
2       98
3       65
4       78
5       98

In [50]:
edf=exam.groupby('nclass').agg(["mean","median"])
edf['id']

        mean  median
nclass
1        2.5     2.5
2        6.5     6.5
3       10.5    10.5
4       14.5    14.5
5       18.5    18.5

In [66]:
edf.columns

MultiIndex([(     'id',   'mean'),
            (     'id', 'median'),
            (   'math',   'mean'),
            (   'math', 'median'),
            ('english',   'mean'),
            ('english', 'median'),
            ('science',   'mean'),
            ('science', 'median')],
           )

In [53]:
edf[["math","science"]]

         math        science
         mean median    mean median
nclass
1       46.25   47.5   61.50   59.0
2       61.25   65.0   58.25   55.0
3       45.00   47.5   39.25   38.5
4       56.75   53.0   55.00   65.0
5       78.00   79.0   83.25   88.5

In [55]:
edf[("science","mean")]

nclass
1    61.50
2    58.25
3    39.25
4    55.00
5    83.25
Name: (science, mean), dtype: float64

In [56]:
#멀티인덱스
edf[[('math','median'),('science','mean')]]

         math science
       median    mean
nclass
1        47.5   61.50
2        65.0   58.25
3        47.5   39.25
4        53.0   55.00
5        79.0   83.25

In [162]:
display_size_by_side(exam.sample(6),exam.groupby('nclass'),exam.groupby('nclass',))

NameError: name 'display_size_by_side' is not defined

In [67]:
#agg()인자 사용법, 열 이름은 키워드인 반면, 값('열명','힘수명')은 열에서 값을 계산한느데 사용되는 이름
# 새_열이름=('열명','함수명')

In [164]:
exam.groupby('nclass').agg({'math':['mean',"count"]})

         math
         mean count
nclass
1       46.25     4
2       61.25     4
3       45.00     4
4       56.75     4
5       78.00     4

In [72]:
##@@@@@ 인덱스로 안 넣고 데이터 프레임 열로 넣는것 : as_index()
exam.groupby('nclass').agg(mean_math=('math','mean'))

        mean_math
nclass
1           46.25
2           61.25
3           45.00
4           56.75
5           78.00

In [71]:
exam.groupby('nclass',as_index=False).agg(mean_math=('math','mean'))

   nclass  mean_math
0       1      46.25
1       2      61.25
2       3      45.00
3       4      56.75
4       5      78.00

In [166]:
#@@@@
exam.groupby('nclass').agg(mena_math=('math','mean'))

        mena_math
nclass
1           46.25
2           61.25
3           45.00
4           56.75
5           78.00

In [57]:
#2교시
exam.groupby('nclass')

In [58]:
type(exam.groupby('nclass'))

pandas.core.groupby.generic.DataFrameGroupBy

In [59]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [61]:
exam_gb=exam.groupby('nclass')
exam_gb

In [62]:
list(exam_gb)

[(1,
     id  nclass  math  english  science
  0   1       1    50       98       50
  1   2       1    60       97       60
  2   3       1    45       86       78
  3   4       1    30       98       58),
 (2,
     id  nclass  math  english  science
  4   5       2    25       80       65
  5   6       2    50       89       98
  6   7       2    80       90       45
  7   8       2    90       78       25),
 (3,
      id  nclass  math  english  science
  8    9       3    20       98       15
  9   10       3    50       98       45
  10  11       3    65       65       65
  11  12       3    45       85       32),
 (4,
      id  nclass  math  english  science
  12  13       4    46       98       65
  13  14       4    48       87       12
  14  15       4    75       56       78
  15  16       4    58       98       65),
 (5,
      id  nclass  math  english  science
  16  17       5    65       68       98
  17  18       5    80       78       90
  18  19       5    89       68       87
  19  20       5    78       83       58)]

In [64]:
#.groups 는 무엇인가
exam_gb.groups

{1: [0, 1, 2, 3], 2: [4, 5, 6, 7], 3: [8, 9, 10, 11], 4: [12, 13, 14, 15], 5: [16, 17, 18, 19]}

In [74]:
for key, value in exam_gb:
  print(f'key:{key}')
  print(f'type(value):[type(value)]')
  print(f'value:\n {value}')
  print('='*40,'\n')

key:1
type(value):[type(value)]
value:
    id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
========================================

key:2
type(value):[type(value)]
value:
    id  nclass  math  english  science
4   5       2    25       80       65
5   6       2    50       89       98
6   7       2    80       90       45
7   8       2    90       78       25
========================================

key:3
type(value):[type(value)]
value:
     id  nclass  math  english  science
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
========================================

key:4
type(value):[type(value)]
value:
     id  nclass  math  english  science
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
========================================

key:5
type(value):[type(value)]
value:
     id  nclass  math  english  science
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58
========================================

In [75]:
#여러 요약 통계량 한 번에 구하기
#nclass 별로 분리 : 수학 점수 평균, 수하 점수 합계, 수학 점수 중앙값, 빈도(학생 수)
exam.groupby('nclass').agg(mean_math=('math','mean'),
                           sum_math=('math','sum'),
                           median_math=('math','median'),
                           count=('nclass','count'))

        mean_math  sum_math  median_math  count
nclass
1           46.25       185         47.5      4
2           61.25       245         65.0      4
3           45.00       180         47.5      4
4           56.75       227         53.0      4
5           78.00       312         79.0      4

In [76]:
###@@@@모든 변수의 요약 통계량 한번에 구학
exam.groupby('nclass').mean()

          id   math  english  science
nclass
1        2.5  46.25    94.75    61.50
2        6.5  61.25    84.25    58.25
3       10.5  45.00    86.50    39.25
4       14.5  56.75    84.75    55.00
5       18.5  78.00    74.25    83.25

In [77]:
#agg()넣어서 여러개 값 가질수있음
exam.groupby('nclass').agg(['mean','median'])

          id          math        english        science
        mean median   mean median    mean median    mean median
nclass
1        2.5    2.5  46.25   47.5   94.75   97.5   61.50   59.0
2        6.5    6.5  61.25   65.0   84.25   84.5   58.25   55.0
3       10.5   10.5  45.00   47.5   86.50   91.5   39.25   38.5
4       14.5   14.5  56.75   53.0   84.75   92.5   55.00   65.0
5       18.5   18.5  78.00   79.0   74.25   73.0   83.25   88.5

In [81]:
display_series_side_by_side(exam.head(),exam.tail())

AttributeError: 'DataFrame' object has no attribute 'to_frame'

In [84]:
#집단별로 다시 집단 나누기
#mpg : 자동차 정보 스펙 데이터
import pandas as pd

mpg=pd.read_csv('data/mpg.csv')
print(mpg.head())
print(mpg.info())
print(mpg.tail())

  manufacturer model  displ  year  cyl       trans drv  cty  hwy fl category
0         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
2         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
3         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
4         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   manufacturer  234 non-null    object
 1   model         234 non-null    object
 2   displ         234 non-null    float64
 3   year          234 non-null    int64
 4   cyl           234 non-null    int64
 5   trans         234 non-null    object
 6   drv           234 non-null    object
 7   cty           234 non-null    int64
 8   hwy           234 non-null    int64
 9   fl            234 non-null    object
 10  category      234 non-null    object
dtypes: float64(1), int64(4), object(6)
memory usage: 20.2+ KB
None
    manufacturer   model  displ  year  cyl       trans drv  cty  hwy fl  \
229   volkswagen  passat    2.0  2008    4    auto(s6)   f   19   28  p
230   volkswagen  passat    2.0  2008    4  manual(m6)   f   21   29  p
231   volkswagen  passat    2.8  1999    6    auto(l5)   f   16   26  p
232   volkswagen  passat    2.8  1999    6  manual(m5)   f   18   26  p
233   volkswagen  passat    3.6  2008    6    auto(s6)   f   17   26  p

    category
229  midsize
230  midsize
231  midsize
232  midsize
233  midsize

In [86]:
!pip install pydataset
from pydataset import data

Collecting pydataset
  Downloading pydataset-0.2.0.tar.gz (15.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.9/15.9 MB 34.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pydataset) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->pydataset) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pydataset) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pydataset) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pydataset) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pydataset) (1.17.0)
Building wheels for collected packages: pydataset
  Building wheel for pydataset (setup.py) ... done
  Created wheel for pydataset: filename=pydataset-0.2.0-py3-none-any.whl size=15939415 sha256=13797119b6e856b4b8f94a3a07012ce37fe75a68f16cbeff4eba9e450cc92585
  Stored in directory: /root/.cache/pip/wheels/4c/82/ad/f04abc617222b10438b1285ab9b5cfaecd180c10a7c81cff54
Successfully built pydataset
Installing collected packages: pydataset
Successfully installed pydataset-0.2.0
initiated datasets repo at: /root/.pydataset/

In [87]:
mpg2=data('mpg')
mpg2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 234 entries, 1 to 234
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   manufacturer  234 non-null    object
 1   model         234 non-null    object
 2   displ         234 non-null    float64
 3   year          234 non-null    int64
 4   cyl           234 non-null    int64
 5   trans         234 non-null    object
 6   drv           234 non-null    object
 7   cty           234 non-null    int64
 8   hwy           234 non-null    int64
 9   fl            234 non-null    object
 10  class         234 non-null    object
dtypes: float64(1), int64(4), object(6)
memory usage: 21.9+ KB

In [88]:
mpg.columns

Index(['manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty',
       'hwy', 'fl', 'category'],
      dtype='object')

In [90]:
#2%를 랜덤으로 가져오는 것
mpg.sample(frac=.02)

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
18,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,14,20,r,suv
107,honda,civic,2.0,2008,4,manual(m6),f,21,29,p,subcompact
167,subaru,impreza awd,2.5,1999,4,manual(m5),4,19,26,r,subcompact
220,volkswagen,jetta,2.8,1999,6,manual(m5),f,17,24,r,compact
140,mercury,mountaineer 4wd,5.0,1999,8,auto(l4),4,13,17,r,suv

In [91]:
#@@@@@
#제조 회사 및 구동 방식별 분리, cty평균 구하기
#agg()에 cty어딨나???
mpg.groupby(['manufacturer','drv']).agg(mean_cty=('cty','mean'))

                   mean_cty
manufacturer drv
audi         4    16.818182
             f    18.857143
chevrolet    4    12.500000
             f    18.800000
             r    14.100000
dodge        4    12.000000
             f    15.818182
ford         4    13.307692
             r    14.750000
honda        f    24.444444
hyundai      f    18.642857
jeep         4    13.500000
land rover   4    11.500000
lincoln      r    11.333333
mercury      4    13.250000
nissan       4    13.750000
             f    20.000000
pontiac      f    17.000000
subaru       4    19.285714
toyota       4    14.933333
             f    21.368421
volkswagen   f    20.925926

In [92]:
mpg.groupby(['drv','manufacturer']).agg(mean_cty=('cty','mean'))

                   mean_cty
drv manufacturer
4   audi          16.818182
    chevrolet     12.500000
    dodge         12.000000
    ford          13.307692
    jeep          13.500000
    land rover    11.500000
    mercury       13.250000
    nissan        13.750000
    subaru        19.285714
    toyota        14.933333
f   audi          18.857143
    chevrolet     18.800000
    dodge         15.818182
    honda         24.444444
    hyundai       18.642857
    nissan        20.000000
    pontiac       17.000000
    toyota        21.368421
    volkswagen    20.925926
r   chevrolet     14.100000
    ford          14.750000
    lincoln       11.333333

In [94]:
mdf=mpg.groupby(['drv','manufacturer']).agg(mean_cty=('cty','mean'))
mdf.sort_values('mean_cty',ascending=False)

                   mean_cty
drv manufacturer
f   honda         24.444444
    toyota        21.368421
    volkswagen    20.925926
    nissan        20.000000
4   subaru        19.285714
f   audi          18.857143
    chevrolet     18.800000
    hyundai       18.642857
    pontiac       17.000000
4   audi          16.818182
f   dodge         15.818182
4   toyota        14.933333
r   ford          14.750000
    chevrolet     14.100000
4   nissan        13.750000
    jeep          13.500000
    ford          13.307692
    mercury       13.250000
    chevrolet     12.500000
    dodge         12.000000
    land rover    11.500000
r   lincoln       11.333333

In [95]:
#4륜,전륜(f),후륜(r) 중에서 여니 순으로 정렬
mdf.sort_values(['drv','mean_cty'],ascending=[True,False])

                   mean_cty
drv manufacturer
4   subaru        19.285714
    audi          16.818182
    toyota        14.933333
    nissan        13.750000
    jeep          13.500000
    ford          13.307692
    mercury       13.250000
    chevrolet     12.500000
    dodge         12.000000
    land rover    11.500000
f   honda         24.444444
    toyota        21.368421
    volkswagen    20.925926
    nissan        20.000000
    audi          18.857143
    chevrolet     18.800000
    hyundai       18.642857
    pontiac       17.000000
    dodge         15.818182
r   ford          14.750000
    chevrolet     14.100000
    lincoln       11.333333

In [96]:
mdf.index

MultiIndex([('4',       'audi'),
            ('4',  'chevrolet'),
            ('4',      'dodge'),
            ('4',       'ford'),
            ('4',       'jeep'),
            ('4', 'land rover'),
            ('4',    'mercury'),
            ('4',     'nissan'),
            ('4',     'subaru'),
            ('4',     'toyota'),
            ('f',       'audi'),
            ('f',  'chevrolet'),
            ('f',      'dodge'),
            ('f',      'honda'),
            ('f',    'hyundai'),
            ('f',     'nissan'),
            ('f',    'pontiac'),
            ('f',     'toyota'),
            ('f', 'volkswagen'),
            ('r',  'chevrolet'),
            ('r',       'ford'),
            ('r',    'lincoln')],
           names=['drv', 'manufacturer'])

In [100]:
#제조 회사 vs 차종별 분리
#cty 평균, hwy평균
mpg.groupby(['manufacturer','category']).agg(mean_cty=('cty','mean'),mean_hwy=('hwy','mean'))

                          mean_cty   mean_hwy
manufacturer category
audi         compact     17.933333  26.933333
             midsize     16.000000  24.000000
chevrolet    2seater     15.400000  24.800000
             midsize     18.800000  27.600000
             suv         12.666667  17.111111
dodge        minivan     15.818182  22.363636
             pickup      12.052632  16.105263
             suv         11.857143  16.000000
ford         pickup      13.000000  16.428571
             subcompact  15.888889  23.222222
             suv         12.888889  17.777778
honda        subcompact  24.444444  32.555556
hyundai      midsize     19.000000  27.714286
             subcompact  18.285714  26.000000
jeep         suv         13.500000  17.625000
land rover   suv         11.500000  16.500000
lincoln      suv         11.333333  17.000000
mercury      suv         13.250000  18.000000
nissan       compact     20.000000  28.000000
             midsize     20.000000  27.428571
             suv         13.750000  18.000000
pontiac      midsize     17.000000  26.400000
subaru       compact     19.750000  26.000000
             subcompact  19.500000  26.000000
             suv         18.833333  25.000000
toyota       compact     22.250000  30.583333
             midsize     19.857143  28.285714
             pickup      15.571429  19.428571
             suv         14.375000  18.250000
volkswagen   compact     20.785714  28.500000
             midsize     18.571429  27.571429
             subcompact  24.000000  32.833333

In [104]:
#
mpg.query('manufacturer=="audo"').groupby(['drv']).agg(n=('drv','count'))

Empty DataFrame
Columns: [n]
Index: []

In [106]:
#@@@
mpg[ (mpg.manufacturer== "audi")& (mpg.drv.isin(['4','r','f']))]

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
5,audi,a4,2.8,1999,6,manual(m5),f,18,26,p,compact
6,audi,a4,3.1,2008,6,auto(av),f,18,27,p,compact
7,audi,a4 quattro,1.8,1999,4,manual(m5),4,18,26,p,compact
8,audi,a4 quattro,1.8,1999,4,auto(l5),4,16,25,p,compact
9,audi,a4 quattro,2.0,2008,4,manual(m6),4,20,28,p,compact
10,audi,a4 quattro,2.0,2008,4,auto(s6),4,19,27,p,compact
11,audi,a4 quattro,2.8,1999,6,auto(l5),4,15,25,p,compact
12,audi,a4 quattro,2.8,1999,6,manual(m5),4,17,25,p,compact
13,audi,a4 quattro,3.1,2008,6,auto(s6),4,17,25,p,compact
14,audi,a4 quattro,3.1,2008,6,manual(m6),4,15,25,p,compact
15,audi,a6 quattro,2.8,1999,6,auto(l5),4,15,24,p,midsize
16,audi,a6 quattro,3.1,2008,6,auto(s6),4,17,25,p,midsize
17,audi,a6 quattro,4.2,2008,8,auto(s6),4,16,23,p,midsize

In [109]:
#
mpg.query("manufacturer== 'audi' and drv in ['4','r','f']")

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
5,audi,a4,2.8,1999,6,manual(m5),f,18,26,p,compact
6,audi,a4,3.1,2008,6,auto(av),f,18,27,p,compact
7,audi,a4 quattro,1.8,1999,4,manual(m5),4,18,26,p,compact
8,audi,a4 quattro,1.8,1999,4,auto(l5),4,16,25,p,compact
9,audi,a4 quattro,2.0,2008,4,manual(m6),4,20,28,p,compact
10,audi,a4 quattro,2.0,2008,4,auto(s6),4,19,27,p,compact
11,audi,a4 quattro,2.8,1999,6,auto(l5),4,15,25,p,compact
12,audi,a4 quattro,2.8,1999,6,manual(m5),4,17,25,p,compact
13,audi,a4 quattro,3.1,2008,6,auto(s6),4,17,25,p,compact
14,audi,a4 quattro,3.1,2008,6,manual(m6),4,15,25,p,compact
15,audi,a6 quattro,2.8,1999,6,auto(l5),4,15,24,p,midsize
16,audi,a6 quattro,3.1,2008,6,auto(s6),4,17,25,p,midsize
17,audi,a6 quattro,4.2,2008,8,auto(s6),4,16,23,p,midsize

In [110]:
# chevrolet의 drv별 빈도
#chevrolet 추출
# drv 빈도

mpg.query('manufacturer== "chevrolet"')\
  .groupby(['drv']).agg(n=('drv','count'))

      n
drv
4     4
f     5
r    10

In [111]:
mpg.query('manufacturer== "chevrolet"').groupby(['drv']).count()[['model']

SyntaxError: incomplete input (3100896325.py, line 1)

In [112]:
#시리즈는 쿼리 사용 불가
mpg.query('manufacturer =="chevrolet"').groupby(['drv']).count()[['model']].rename(columns={'model':'n'})

      n
drv
4     4
f     5
r    10

In [113]:
#@@@2 value_counts()
mpg.groupby('drv').agg(n=('drv','count'))

       n
drv
4    103
f    106
r     25

In [114]:
mpg[['drv','cyl']].value_counts()

drv  cyl
f    4      58
4    8      48
f    6      43
4    6      32
     4      23
r    8      21
f    5       4
r    6       4
f    8       1
Name: count, dtype: int64

In [115]:
mpg['drv'].value_counts().query('count>100')

AttributeError: 'Series' object has no attribute 'query'

In [116]:
mpg['drv'].value_counts().to_frame().query('count >100')

     count
drv
f      106
4      103

3교시 :

In [167]:
mpg['drv'].value_counts()\
  .to_frame('n')

       n
drv
f    106
4    103
r     25

In [168]:
#
mpg['drv'].value_counts() \
  .to_frame('n')\
  .query('n>100')

       n
drv
f    106
4    103

In [169]:
mpg.groupby('drv').agg(n=('drv','count'))

       n
drv
4    103
f    106
r     25

In [170]:
mpg.groupby('drv').agg(n=('drv','count')).query('n>100')

       n
drv
4    103
f    106

In [174]:
###@@@@ .assign()
##pandas함수 조합
 ## suv추출, 합산 연비 변수 만들기->제조 회사별로 분리->합산 변비 평균 구하기
mpg.query('category== "suv"')\
  .assign(total=(mpg['hwy']+mpg['cty'])/2)\
  .groupby('manufacturer')\
  .agg(mean_tot=('total','mean'))\
  .sort_values('mean_tot',ascending=False)\
  .head(5)

               mean_tot
manufacturer
subaru        21.916667
toyota        16.312500
nissan        15.875000
mercury       15.625000
jeep          15.562500

In [ ]:
mpg.query('category=="suv"')\
  .assign(total=(mpg['hwy'+mpg['cty']]))

In [175]:
# 중간고사 데이터 만들기
test1 = pd.DataFrame({'id'      : [1, 2, 3, 4, 5],
                      'midterm' : [60, 80, 70, 90, 85]})

# 기말고사 데이터 만들기
test2 = pd.DataFrame({'id'    : [1, 2, 3, 4, 5],
                      'final' : [70, 83, 65, 95, 80]})

In [177]:
#
display_side_by_side(test1,test2)

,id,midterm
0,1,60
1,2,80
2,3,70
3,4,90
4,5,85
,id,final
0,1,70
1,2,83
2,3,65
3,4,95
4,5,80

In [176]:
#@@@ .merge()
pd.merge(test1,test2)

   id  midterm  final
0   1       60     70
1   2       80     83
2   3       70     65
3   4       90     95
4   5       85     80

In [178]:
pd.merge(test1,test2,on='id')

   id  midterm  final
0   1       60     70
1   2       80     83
2   3       70     65
3   4       90     95
4   5       85     80

In [179]:
pd.merge(test1,test2,on='id',how='inner')

   id  midterm  final
0   1       60     70
1   2       80     83
2   3       70     65
3   4       90     95
4   5       85     80

In [180]:
test1.merge(test2,on='id',how='inner')

   id  midterm  final
0   1       60     70
1   2       80     83
2   3       70     65
3   4       90     95
4   5       85     80

In [183]:
name = pd.DataFrame({'nclass'  : [1, 2, 3, 4, 5],
                     'teacher' : ['kim', 'lee', 'park', 'choi', 'jung']})

In [184]:
exam.sample(5)

    id  nclass  math  english  science
8    9       3    20       98       15
19  20       5    78       83       58
5    6       2    50       89       98
0    1       1    50       98       50
17  18       5    80       78       90

In [185]:
display_side_by_side(exam.sample(5),name)

In [186]:
pd.merge(exam,name,on='nclass',how='inner')

    id  nclass  math  english  science teacher
0    1       1    50       98       50     kim
1    2       1    60       97       60     kim
2    3       1    45       86       78     kim
3    4       1    30       98       58     kim
4    5       2    25       80       65     lee
5    6       2    50       89       98     lee
6    7       2    80       90       45     lee
7    8       2    90       78       25     lee
8    9       3    20       98       15    park
9   10       3    50       98       45    park
10  11       3    65       65       65    park
11  12       3    45       85       32    park
12  13       4    46       98       65    choi
13  14       4    48       87       12    choi
14  15       4    75       56       78    choi
15  16       4    58       98       65    choi
16  17       5    65       68       98    jung
17  18       5    80       78       90    jung
18  19       5    89       68       87    jung
19  20       5    78       83       58    jung

In [187]:
#서로 합치기 concat()
# 학생 1~5번 시험 데이터 만들기
group_a = pd.DataFrame({'id'   : [1, 2, 3, 4, 5],
                        'test' : [60, 80, 70, 90, 85]})

# 학생 6~10번 시험 데이터 만들기
group_b = pd.DataFrame({'id'   : [6, 7, 8, 9, 10],
                        'test' : [70, 83, 65, 95, 80]})

In [188]:
display_side_by_side(group_a,group_b)

,id,test
0,1,60
1,2,80
2,3,70
3,4,90
4,5,85
,id,test
0,6,70
1,7,83
2,8,65
3,9,95
4,10,80

In [190]:
#reset_index()는 인덱스가
pd.concat([group_a,group_b])
#아래 쓸데없이 길어지는 문제 발생

   id  test
0   1    60
1   2    80
2   3    70
3   4    90
4   5    85
0   6    70
1   7    83
2   8    65
3   9    95
4  10    80

In [191]:
#reset_index() : 인덱스를 다시 0,1,2,3형태로 초기화하는 함수
pd.concat([group_a,group_b]).reset_index()

   index  id  test
0      0   1    60
1      1   2    80
2      2   3    70
3      3   4    90
4      4   5    85
5      0   6    70
6      1   7    83
7      2   8    65
8      3   9    95
9      4  10    80

In [193]:
pd.concat([group_a,group_b]).reset_index(drop=True)

   id  test
0   1    60
1   2    80
2   3    70
3   4    90
4   5    85
5   6    70
6   7    83
7   8    65
8   9    95
9  10    80

In [196]:
#merge() @@@@
import pandas as pd
df1=pd.DataFrame([
    [1,'apple'],
    [2,'banana']],columns=['id','fruits'])
df1

   id  fruits
0   1   apple
1   2  banana

In [197]:
df2=pd.DataFrame([[1,3000],[2,500]],columns=['id','price'])
df2

   id  price
0   1   3000
1   2    500

In [198]:
display_side_by_side(df1,df2)

,id,fruits
0,1,apple
1,2,banana
,id,price
0,1,3000
1,2,500

In [199]:
pd.merge(df1,df2,how='inner')

   id  fruits  price
0   1   apple   3000
1   2  banana    500

In [200]:
display_side_by_side(df1,df2)

,id,fruits
0,1,apple
1,2,banana
,id,price
0,1,3000
1,2,500

In [201]:
df1.merge(df2)

   id  fruits  price
0   1   apple   3000
1   2  banana    500

In [209]:
display_side_by_side(df1,df2,df1.merge(df2,how='right'),pd.merge(df1,df2,how='left'),
df1.merge(df2,how='left')))

SyntaxError: unmatched ')' (3538893640.py, line 2)

In [203]:
#how='left'  ? 왼쪽을 기준으로 합치기
df1.merge(df2,how='left')

   id  fruits  price
0   1   apple   3000
1   2  banana    500

In [210]:
display_side_by_side(df1, df2, df1.merge(df2, how='right'))

In [211]:
#how='cross'모든 조합을 다 만든다
display_side_by_side(df1,df2,df1.merge(df2,how='outer'))

In [212]:
df1.merge(df2,how='cross')

   id_x  fruits  id_y  price
0     1   apple     1   3000
1     1   apple     2    500
2     2  banana     1   3000
3     2  banana     2    500

In [213]:
display_side_by_side(df1,df2,df1.merge(df2,how='cross'))

In [216]:
#이너조인, 아우터조인, left join, right join
df1 = pd.DataFrame([[1, 'a1'], [2, 'a2']], columns = ['ID', 'X1'])
df2 = pd.DataFrame([[2, 'b1'], [3, 'b2']], columns = ['ID', 'X2'])

In [217]:
display_side_by_side(df1,df2,df1.merge(df2))

In [218]:
display_side_by_side(df1,df2,df1.merge(df2,how='inner'))

In [219]:
display_side_by_side(df1,df2,df1.merge(df2,how='left'))

In [220]:
display_side_by_side(df1,df2,df1.merge(df2,how='right'))

In [221]:
display_side_by_side(df1,df2,df1.merge(df2,how='outer'))

In [222]:
display_side_by_side(df1,df2,df1.merge(df2,how='cross'))

In [223]:
#정리하기
exam.assign(total=exam['math']+exam['english']+exam['science'])\
  .sort_values('total').head()

    id  nclass  math  english  science  total
8    9       3    20       98       15    133
13  14       4    48       87       12    147
11  12       3    45       85       32    162
4    5       2    25       80       65    170
3    4       1    30       98       58    186

In [224]:
exam.groupby('nclass').agg(mena_math=('math','mean'))

        mena_math
nclass
1           46.25
2           61.25
3           45.00
4           56.75
5           78.00

In [226]:
mpg.groupby(['manufacturer','drv']).agg(mean_cty=('cty','mean'))

                   mean_cty
manufacturer drv
audi         4    16.818182
             f    18.857143
chevrolet    4    12.500000
             f    18.800000
             r    14.100000
dodge        4    12.000000
             f    15.818182
ford         4    13.307692
             r    14.750000
honda        f    24.444444
hyundai      f    18.642857
jeep         4    13.500000
land rover   4    11.500000
lincoln      r    11.333333
mercury      4    13.250000
nissan       4    13.750000
             f    20.000000
pontiac      f    17.000000
subaru       4    19.285714
toyota       4    14.933333
             f    21.368421
volkswagen   f    20.925926

In [227]:
pd.merge(test1,test2,how='left',on='id')

   id  midterm  final
0   1       60     70
1   2       80     83
2   3       70     65
3   4       90     95
4   5       85     80

In [228]:
pd.concat([group_a,group_b])

   id  test
0   1    60
1   2    80
2   3    70
3   4    90
4   5    85
0   6    70
1   7    83
2   8    65
3   9    95
4  10    80