<a href="https://colab.research.google.com/github/dwelle511/2026BDA/blob/main/BDA_Day06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##6.2 DataFrane 생성

In [ ]:
#@@@Series 로 DataFrame생성 중간
import pandas as pd
course=pd.Series(["Spark","PySpark","Haddop"],name='courses')
course

0      Spark
1    PySpark
2     Haddop
Name: courses, dtype: object

In [ ]:
##DataFrame : 형성시 [] 인가 {} 둘다 인가 왜 되지?? 여러 타입을 인자로 가질수
#잇어서 인가? 그럼 안되는 인자는 뭐더라
fees=pd.Series([250000,300000,200000],name='fees')
fees

0    250000
1    300000
2    200000
Name: fees, dtype: int64

In [ ]:
df=pd.DataFrame({course.name:course,fees.name:fees})
df

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Haddop  200000

In [ ]:
course=pd.Series(["Spark","PySpark","Hadoop"],name='course')
fees=pd.Series([250000,300000,200000],name='fees')

df=pd.concat([course,fees],axis=1)
df

    course    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop  200000

In [ ]:
#object는 문자열 임
courses=pd.Series(["Spark","PySpark","Hadoop"],name='courses')
fees=pd.Series([250000,300000,200000],name='fees')

df=pd.concat([courses,fees])
df

0      Spark
1    PySpark
2     Hadoop
0     250000
1     300000
2     200000
dtype: object

In [ ]:
#다양한 데이터 프레임 생성 방법
courses=pd.Series(["Spark","PySpark","Hadoop"],name='courses')
fees=pd.Series([250000,300000,200000],name='fees')

df=pd.DataFrame([courses,fees])
df

              0        1       2
courses   Spark  PySpark  Hadoop
fees     250000   300000  200000

In [ ]:
df.T

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop  200000

In [ ]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
courses=pd.Series(["Spakr","PySpark","Hadoop"],name='courses')
df[courses.name]=courses

df

   courses
0    Spakr
1  PySpark
2   Hadoop

In [ ]:
fees=pd.Series([250000,300000,200000],name='fees')
df[fees.name]=fees
df

   courses    fees
0    Spakr  250000
1  PySpark  300000
2   Hadoop  200000

In [ ]:
#여러 dict의 목록 데이터 사용
#
import pandas as pd

df=pd.DataFrame({"국어":[82,54,45],'수학':[99,67,57]},index=["김국진","신영화","이길순"])
df

     국어  수학
김국진  82  99
신영화  54  67
이길순  45  57

In [ ]:
df.index

Index(['김국진', '신영화', '이길순'], dtype='object')

In [ ]:
df.columns

Index(['국어', '수학'], dtype='object')

In [ ]:
df=pd.DataFrame({'numbers':[1,2,3],'colors':['red','white','blue']})
df

   numbers colors
0        1    red
1        2  white
2        3   blue

In [ ]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df.columns

Index(['numbers', 'colors'], dtype='object')

In [ ]:
#다양한 데이터 프렘 생성 방법
#하나의 시리즈가 행이 됨, 시리즈의 name은 행의index된다
import pandas as pd

courses=pd.Series(["spark","pyspark","hadoop"],name='courses')
fees=pd.Series([250000,300000,200000],name='fees')
df=pd.DataFrame([courses,fees])
df

              0        1       2
courses   spark  pyspark  hadoop
fees     250000   300000  200000

In [ ]:
#dict목록 데이터 사용
import pandas as pd

df=pd.DataFrame([{'korea':70,'math':89,'english':90},
                {'korea':80,'english':99},
                {'math':66,'english':78}])
df

   korea  math  english
0   70.0  89.0       90
1   80.0   NaN       99
2    NaN  66.0       78

In [ ]:
import pandas

In [ ]:
#68 9599 = 81 99.7// 68 = 42 95 45

In [ ]:
#다양한 자료형을 구성된 데이터프레임
#데이터 프레임 Df2
#@@@@

import pandas as pd
import numpy as np
df2=pd.DataFrame({
    "a":1.0,
    "b":pd.Timestamp("20260302"),
    "c":pd.Series(np.arange(1,3,.5)),
    "d":np.array([3]*4,dtype='int32'),
    "e":pd.Categorical(["test","train","test","train"]),
    "f":"foo"

})
df2

     a          b    c  d      e    f
0  1.0 2026-03-02  1.0  3   test  foo
1  1.0 2026-03-02  1.5  3  train  foo
2  1.0 2026-03-02  2.0  3   test  foo
3  1.0 2026-03-02  2.5  3  train  foo

6.3.DataFrame 다양한 참조

In [ ]:
#데이터 프레임 열 참조
import pandas as pd
pf=pd.DataFrame(data=[[25,33,22,11],
                      [11,22,33,44],
                      [11,22,33,44],
                      [11,22,33,44],
                      [11,22,33,44]],
                index=['윤일형','강수희','홍소희','유한빈','신수빈'],
                columns=['mid','end','paper','attend'])

pf

     mid  end  paper  attend
윤일형   25   33     22      11
강수희   11   22     33      44
홍소희   11   22     33      44
유한빈   11   22     33      44
신수빈   11   22     33      44

In [ ]:
pf.mid

윤일형    25
강수희    11
홍소희    11
유한빈    11
신수빈    11
Name: mid, dtype: int64

In [ ]:
#시리즈로 반환 , 데이터 프레임으로 반환
pf["mid"] #문자열-> 시리즈

윤일형    25
강수희    11
홍소희    11
유한빈    11
신수빈    11
Name: mid, dtype: int64

In [ ]:
pf[['mid']] # 리스트ㅡ -> 데이터 프레임

     mid
윤일형   25
강수희   11
홍소희   11
유한빈   11
신수빈   11

In [ ]:
pf[['end','attend','mid']]

     end  attend  mid
윤일형   33      11   25
강수희   22      44   11
홍소희   22      44   11
유한빈   22      44   11
신수빈   22      44   11

In [ ]:
pf[['paper']]

     paper
윤일형     22
강수희     33
홍소희     33
유한빈     33
신수빈     33

In [ ]:
#조건에 맞는 행 참조
import pandas as pd
pf=pd.DataFrame(data=[[25,33,22,11],
                      [11,22,33,44],
                      [11,22,33,44],
                      [11,22,33,44],
                      [11,22,33,44]],
                index=['윤일형','강수희','홍소희','유한빈','신수빈'],
                columns=['mid','end','paper','attend'])

pf

     mid  end  paper  attend
윤일형   25   33     22      11
강수희   11   22     33      44
홍소희   11   22     33      44
유한빈   11   22     33      44
신수빈   11   22     33      44

In [ ]:
pf['mid']>10

윤일형    True
강수희    True
홍소희    True
유한빈    True
신수빈    True
Name: mid, dtype: bool

In [ ]:
pf[pf['mid']>20]

     mid  end  paper  attend
윤일형   25   33     22      11

In [ ]:
#
pf[pf['attend']>=19]

     mid  end  paper  attend
강수희   11   22     33      44
홍소희   11   22     33      44
유한빈   11   22     33      44
신수빈   11   22     33      44

In [ ]:
pf[pf]

In [ ]:
#df.loc[]
import pandas as pd
pf=pd.DataFrame(data=[[25,33,22,11],
                      [11,22,33,44],
                      [11,22,33,44],
                      [11,22,33,44],
                      [11,22,33,44]],
                index=['윤일형','강수희','홍소희','유한빈','신수빈'],
                columns=['mid','end','paper','attend'])

pf

     mid  end  paper  attend
윤일형   25   33     22      11
강수희   11   22     33      44
홍소희   11   22     33      44
유한빈   11   22     33      44
신수빈   11   22     33      44

In [ ]:
df.loc['윤일형']

KeyError: '윤일형'

In [ ]:
#loc[index[i]행 참조 @@@@@
#pf.loc[pf.index[0]] 으로 첫 번째의 행 결과를 시리즈로 반환
pf.loc[pf.index[0]] # 첫 번째 행 검색

mid       25
end       33
paper     22
attend    11
Name: 윤일형, dtype: int64

In [ ]:
pf.loc[[pf.index[0]]] # 첫 번째 행 검색

     mid  end  paper  attend
윤일형   25   33     22      11

In [ ]:
pf.loc[[pf.index[0]]] #첫 번재 행 검색

     mid  end  paper  attend
윤일형   25   33     22      11

In [ ]:
pf.loc[pf.index[1:4]] #슬라이싱 행 검색

     mid  end  paper  attend
강수희   11   22     33      44
홍소희   11   22     33      44
유한빈   11   22     33      44

In [ ]:
pf.loc[pf.index[1:4]][['mid','paper']]

     mid  paper
강수희   11     33
홍소희   11     33
유한빈   11     33

In [ ]:
#열 참조
#pf.loc[:colname] :열명 전체를 시리즈로 반환
df.loc[:'paper']

   numbers colors
0        1    red
1        2  white
2        3   blue

In [ ]:
#loc[:columns[i]]로 열 참조
#df.loc[:pf.columns[0]]으로 첫번째 열 결과를 시리즈로반환
#df.columns[0]은 첫번째 열 이름을 반환
pf

     mid  end  paper  attend
윤일형   25   33     22      11
강수희   11   22     33      44
홍소희   11   22     33      44
유한빈   11   22     33      44
신수빈   11   22     33      44

In [ ]:
pf.loc[:,pf.columns[0]]

윤일형    25
강수희    11
홍소희    11
유한빈    11
신수빈    11
Name: mid, dtype: int64

In [ ]:
pf.loc[:,[pf.columns[0]]]

     mid
윤일형   25
강수희   11
홍소희   11
유한빈   11
신수빈   11

In [ ]:
pf.loc[:,pf.columns[1:]]

     end  paper  attend
윤일형   33     22      11
강수희   22     33      44
홍소희   22     33      44
유한빈   22     33      44
신수빈   22     33      44

In [ ]:
pf.loc[:,pf.columns[1:3]]

     end  paper
윤일형   33     22
강수희   22     33
홍소희   22     33
유한빈   22     33
신수빈   22     33

In [ ]:
pf.loc[:,pf.columns[1:]][['end','paper']]

     end  paper
윤일형   33     22
강수희   22     33
홍소희   22     33
유한빈   22     33
신수빈   22     33

In [ ]:
#행과 열 참조
#df.loc['행명','열명']
pf.loc['윤일형','attend']

np.int64(11)

In [ ]:
pf.loc['윤일형':'유한빈','mid']

윤일형    25
강수희    11
홍소희    11
유한빈    11
Name: mid, dtype: int64

In [ ]:
pf.loc[pf.index[0],pf.columns[1]]

np.int64(33)

In [ ]:
pf.loc[pf.index[0:3],pf.columns[2]]

윤일형    22
강수희    33
홍소희    33
Name: paper, dtype: int64

In [ ]:
pf.loc[pf.index[0:3],pf.columns[2:]]

     paper  attend
윤일형     22      11
강수희     33      44
홍소희     33      44

In [ ]:
#df.iloc , 행 참조, df.iloc[int]로 정수 index 행 참조
pf.iloc[1]

mid       11
end       22
paper     33
attend    44
Name: 강수희, dtype: int64

In [ ]:
pf.iloc[[1]]

     mid  end  paper  attend
강수희   11   22     33      44

In [ ]:
pf.iloc[[1,3]]

     mid  end  paper  attend
강수희   11   22     33      44
유한빈   11   22     33      44

In [ ]:
pf.iloc[2:]

     mid  end  paper  attend
홍소희   11   22     33      44
유한빈   11   22     33      44
신수빈   11   22     33      44

In [ ]:
#df.iloc[:,정수] 참조, 열참조, df.iloc[:,정수]로 정수 열 참조
pf.iloc[:,2]

윤일형    22
강수희    33
홍소희    33
유한빈    33
신수빈    33
Name: paper, dtype: int64

In [ ]:
pf.iloc[:,[2]]

     paper
윤일형     22
강수희     33
홍소희     33
유한빈     33
신수빈     33

In [ ]:
pf.iloc[:,1:]

     end  paper  attend
윤일형   33     22      11
강수희   22     33      44
홍소희   22     33      44
유한빈   22     33      44
신수빈   22     33      44

In [ ]:
#df.iloc[행번호,열번호]참조
#행과 열 대당하는 원소나 시리즈,데이터프레임 참조열 참조
#df.iloc[행번호,열번호]
pf.iloc[1,1]

np.int64(22)

In [ ]:
pf.iloc[1:3,1:]

     end  paper  attend
강수희   22     33      44
홍소희   22     33      44

In [ ]:
pf.iloc[[1,3,4],1:] ###@@@@

     end  paper  attend
강수희   22     33      44
유한빈   22     33      44
신수빈   22     33      44

In [ ]:
pf.iloc[[1,3,4],[0,1]]

     mid  end
강수희   11   22
유한빈   11   22
신수빈   11   22

In [ ]:
#at['행명','열명']으로 참조
#레이블 기반으로참조 한는 방식으로 단 하나의 원소를 참조
#하나의 값을 참조하므로 속도가 빠름
pf.at['윤일형','paper']

np.int64(22)

In [ ]:
pf.at['유한빈','mid']

np.int64(11)

In [ ]:
pf.at[pf.index[1],'attend']

np.int64(44)

In [ ]:
pf.at[pf.index[3],pf.columns[2]]

np.int64(33)

In [ ]:
#iat[i,j]참조, 정수 첨자 기반으로 참조 방시긍로 단 하나의 원소르 ㄹ참ㅈ
pf.iat[1,2]

np.int64(33)

In [ ]:
pf.iat[2,3]

np.int64(44)

#수업

In [ ]:
#35p
import pandas as pd
pf=pd.DataFrame(data=[[25,35,8,18],
                      [18,27,10,19],
                      [12,22,9,20],
                      [17,17,10,19],
                      [22,34,8,16]],
                index=['윤일형','강수희','홍소희','유한빈','신수빈'],
                columns=['중간','기말','과제','출석'])

pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  19
홍소희  12  22   9  20
유한빈  17  17  10  19
신수빈  22  34   8  16

In [ ]:
pf.loc[:,'과제']

윤일형     8
강수희    10
홍소희     9
유한빈    10
신수빈     8
Name: 과제, dtype: int64

In [ ]:
#열참조
pf.loc[:,'중간':'과제']

     중간  기말  과제
윤일형  25  35   8
강수희  18  27  10
홍소희  12  22   9
유한빈  17  17  10
신수빈  22  34   8

In [ ]:
pf.loc[:,['기말','출석']]

     기말  출석
윤일형  35  18
강수희  27  19
홍소희  22  20
유한빈  17  19
신수빈  34  16

In [ ]:
#@@@@출력결과 시리즈인지 데잍프레임인지 구별
pf.과제 #결과는 시리즈

윤일형     8
강수희    10
홍소희     9
유한빈    10
신수빈     8
Name: 과제, dtype: int64

In [ ]:
pf[['과제']] # 결과를데이터프레임

     과제
윤일형   8
강수희  10
홍소희   9
유한빈  10
신수빈   8

In [ ]:
#loc[:,columns[i]]로 참조, df.loc[:,pf.columns[0]]으로 첫 번째 열 결과를 시리즈로 반환pf
pf.loc[:,pf.columns[0]]

윤일형    25
강수희    18
홍소희    12
유한빈    17
신수빈    22
Name: 중간, dtype: int64

In [ ]:
pf.loc[:,[pf.columns[0]]]

     중간
윤일형  25
강수희  18
홍소희  12
유한빈  17
신수빈  22

In [ ]:
pf.loc[:,pf.columns[1:]]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  19
홍소희  22   9  20
유한빈  17  10  19
신수빈  34   8  16

In [ ]:
pf.loc[:,pf.columns[1:]][['기말','과제']]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  22   9
유한빈  17  10
신수빈  34   8

In [ ]:
#행과 열. 참조, df.loc['행명','열명']으로 행과 열에 맞는 한 원소를 참조
pf.loc['윤일형','출석']

np.int64(18)

In [ ]:
pf.loc['윤일형':'유한빈',"기말"]

윤일형    35
강수희    27
홍소희    22
유한빈    17
Name: 기말, dtype: int64

In [ ]:
pf.loc['윤일형':'유한빈','기말':'과제']

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  22   9
유한빈  17  10

In [ ]:
pf.loc[pf.index[0],pf.columns[1]]

np.int64(35)

In [ ]:
pf.loc[pf.index[0:3],pf.columns[2]]

윤일형     8
강수희    10
홍소희     9
Name: 과제, dtype: int64

In [ ]:
pf.loc[pf.index[0:3],pf.columns[2:]]

     과제  출석
윤일형   8  18
강수희  10  19
홍소희   9  20

In [ ]:
#df.iloc[정수] 참조
#행 참조 df.iloc[정수]로 정수 index행 참조
pf.iloc[1]

중간    18
기말    27
과제    10
출석    19
Name: 강수희, dtype: int64

In [ ]:
pf.iloc[[1]]

     중간  기말  과제  출석
강수희  18  27  10  19

In [ ]:
pf.iloc[[1,3]]

     중간  기말  과제  출석
강수희  18  27  10  19
유한빈  17  17  10  19

In [ ]:
pf.iloc[2:]

     중간  기말  과제  출석
홍소희  12  22   9  20
유한빈  17  17  10  19
신수빈  22  34   8  16

In [ ]:
#df.iloc[:,정수] 첨조
#열참조, df.iloc[:,정수] 로 정수columns열 참조
pf.iloc[:,2] #series

윤일형     8
강수희    10
홍소희     9
유한빈    10
신수빈     8
Name: 과제, dtype: int64

In [ ]:
pf.iloc[:,[2]] #dataframe 결과임

     과제
윤일형   8
강수희  10
홍소희   9
유한빈  10
신수빈   8

In [ ]:
pf.iloc[:,1:]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  19
홍소희  22   9  20
유한빈  17  10  19
신수빈  34   8  16

In [ ]:
#df.iloc[행번호,열번호] 참조
#행과 열에 대당하는 원소난 시리즈, 데이터프레임 참조열 참조
#df.iloc[행번호,열번호]
pf.iloc[1,1]

np.int64(27)

In [ ]:
pf.iloc[1:3,1:]

     기말  과제  출석
강수희  27  10  19
홍소희  22   9  20

In [ ]:
pf.iloc[:,1:]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  19
홍소희  22   9  20
유한빈  17  10  19
신수빈  34   8  16

In [ ]:
pf.iloc[[1,3,4],1:]

     기말  과제  출석
강수희  27  10  19
유한빈  17  10  19
신수빈  34   8  16

In [ ]:
pf.iloc[[1,3,4],[0,1]]

     중간  기말
강수희  18  27
유한빈  17  17
신수빈  22  34

In [ ]:
#at['행명','열명'] 참조, 레입르 기반으로 참조하는 방식으로 단 하나의 원소 참조
# 하나의 값을 참조하므로 속도가 빠른 장점
pf.at['윤일형','과제']

np.int64(8)

In [ ]:
pf.at['유한빈','기말']

np.int64(17)

In [ ]:
#iat[i,j]참조
#정수 첨자 기반 참조 방식으로 단 하나의 원소 참조
pf.iat[1,2]

np.int64(10)

In [ ]:
pf.iat[2,3]

np.int64(20)

In [ ]:
#Sereis 생성 ,키워드 인지 name='first' 로 속성 name지정가능
import numpy as np
import pandas as pd

s=pd.Series([1,3,5,np.nan,6,8],name='first')
s #return value sereis not DataFrame

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [ ]:
print(s.name)
print(s.index)
print(s.values)
print(s.shape)
print(s.size)

first
RangeIndex(start=0, stop=6, step=1)
[ 1.  3.  5. nan  6.  8.]
(6,)
6

In [ ]:
#시리즈 인덱싱과 슬라이싱
#레이블 슬라이싱 s['b':'f'] : b부터 f까지
import numpy as np
import pandas as pd
s=pd.Series([1,3,5,np.nan,6,8],name='first')
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [ ]:
s[5]

np.float64(8.0)

In [ ]:
s[1:5]

1    3.0
2    5.0
3    NaN
4    6.0
Name: first, dtype: float64

In [ ]:
s.index=list('abcdef')
s

a    1.0
b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
Name: first, dtype: float64

In [ ]:
print(s['b'],s['d'])

3.0 nan

In [ ]:
s['c':'e']

c    5.0
d    NaN
e    6.0
Name: first, dtype: float64

In [ ]:
s['b':'f']

b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
Name: first, dtype: float64

In [ ]:
s[0:3]

a    1.0
b    3.0
c    5.0
Name: first, dtype: float64

In [ ]:
s1=s[1:4]
s1

b    3.0
c    5.0
d    NaN
Name: first, dtype: float64

In [ ]:
s1[0]

/tmp/ipykernel_7158/643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

np.float64(3.0)

In [ ]:
s1[0]=10
s1

/tmp/ipykernel_7158/2709485624.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  s1[0]=10

b    10.0
c     5.0
d     NaN
Name: first, dtype: float64

In [ ]:
#시리즈 인덱싱과 슬라이싱 2/2
#새로운 정소 인덱스 부여, 단일색인 s[1]부여된 색인 정수로 참조
#슬라이싱 색인 s[1:3] 0부터 시작하는 기본 색인으로 슬라이싱됨 1에서2 까지
#새로 지정한 정수 라벨로 슬라이싱되지 않음
s

a     1.0
b    10.0
c     5.0
d     NaN
e     6.0
f     8.0
Name: first, dtype: float64

In [ ]:
s.index=np.arange(1,7)
s

1     1.0
2    10.0
3     5.0
4     NaN
5     6.0
6     8.0
Name: first, dtype: float64

In [ ]:
s[1]

np.float64(1.0)

In [ ]:
#s[0] #인텍스 값인지 행 숫자인지
#존재x -> by) 열 이름으로 인식하나옴 근데 " "안쓴는데

KeyError: 0

In [ ]:
s[1:3]

2    10.0
3     5.0
Name: first, dtype: float64

In [ ]:
#시리즈 고급 인덱싱#
# df[[첨자 _목록]]으로 각 원소로 구성된 시리즈를 반환

import pandas as pd
age=pd.Series([9,17,32,45,65,98],index=list('abcedf'),name='age')
age

a     9
b    17
c    32
e    45
d    65
f    98
Name: age, dtype: int64

In [ ]:
age['b']

np.int64(17)

In [ ]:
age[[1,3,5]] #return 시리즈 !

/tmp/ipykernel_7158/2675513065.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  age[[1,3,5]]

b    17
e    45
f    98
Name: age, dtype: int64

In [ ]:
age[['a','f','d']]

a     9
f    98
d    65
Name: age, dtype: int64

In [ ]:
age[['c']]

c    32
Name: age, dtype: int64

In [ ]:
#시리즈 논리 참조= 불리안 인덱싱
#조건 s>0, 논리 결과의 시리즈를 반환
# s[s>0] 조건 연산을 만족하는 값으로 구성된 시리즈를 반환

import pandas as pd
s=pd.Series([3,6,-3,0,-4,8,-7])
s

0    3
1    6
2   -3
3    0
4   -4
5    8
6   -7
dtype: int64

In [ ]:
s>0

0     True
1     True
2    False
3    False
4    False
5     True
6    False
dtype: bool

In [ ]:
s%2==0

0    False
1     True
2    False
3     True
4     True
5     True
6    False
dtype: bool

In [ ]:
s[s>0]

0    3
1    6
5    8
dtype: int64

In [ ]:
s[~(s>0)]

2   -3
3    0
4   -4
6   -7
dtype: int64

In [ ]:
s[s%2==0]

1    6
3    0
4   -4
5    8
dtype: int64

In [ ]:
s[s%2 !=0]

0    3
2   -3
6   -7
dtype: int64

In [ ]:
s[(s>0)&(s%2==0)]

1    6
5    8
dtype: int64