<a href="https://colab.research.google.com/github/dwelle511/2026BDA/blob/main/TenMinNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import numpy as np
import pandas as pd

In [ ]:
dates=pd.date_range("20260101",periods=6)
print(dates)

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df=pd.DataFrame(np.random.randn(6,4),index=dates,columns=list("abcd"))
df

                   a         b         c         d
2026-01-01 -0.516479  1.140821  2.482918  1.181505
2026-01-02 -0.163442 -1.055219 -2.083279 -0.312002
2026-01-03  2.167520 -1.246033 -0.186264 -1.139036
2026-01-04  1.558131  0.211694 -1.461149  0.945696
2026-01-05 -0.085413  2.948778  0.373176 -0.137942
2026-01-06 -0.262776 -0.644237  0.565875 -0.914063

In [ ]:
np.random.randn(4,2)
#radn(row,cols)

array([[-1.01063336, -0.72761461],
       [-0.10509945,  0.02085518],
       [ 0.7873264 , -0.49367878],
       [-0.51898307, -0.73006599]])

In [ ]:
#pd.categorical()

In [ ]:
df2=pd.DataFrame(
    {
        "A":1.0,
        "B":pd.Timestamp("20260102"),
        "C":pd.Series(1,index=list(range(4)),dtype="float32"),
        "D":pd.array([3]*4,dtype="int32"),
        "E":pd.Categorical(["test","train","test","train"]),
        "F":"foo",

    }
)
df2

#DataFrame(o), DateFrame(x)

     A          B    C  D      E    F
0  1.0 2026-01-02  1.0  3   test  foo
1  1.0 2026-01-02  1.0  3  train  foo
2  1.0 2026-01-02  1.0  3   test  foo
3  1.0 2026-01-02  1.0  3  train  foo

In [ ]:
df2.dtypes
#dype 왜 안됨?
#columns of the resulting DataFrame have difference dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [ ]:
# C
#df2.<TAB>

SyntaxError: invalid syntax (1956585904.py, line 2)

In [ ]:
#VIEW DATA
df.head()

                   a         b         c         d
2026-01-01 -0.516479  1.140821  2.482918  1.181505
2026-01-02 -0.163442 -1.055219 -2.083279 -0.312002
2026-01-03  2.167520 -1.246033 -0.186264 -1.139036
2026-01-04  1.558131  0.211694 -1.461149  0.945696
2026-01-05 -0.085413  2.948778  0.373176 -0.137942

In [ ]:
df.tail(3)

                   a         b         c         d
2026-01-04  1.558131  0.211694 -1.461149  0.945696
2026-01-05 -0.085413  2.948778  0.373176 -0.137942
2026-01-06 -0.262776 -0.644237  0.565875 -0.914063

In [ ]:
#display the DataFrame.index or DataFrame.columns
df.index

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
#representation of the underlying data with DataFrame.to_numpy()
# without the index or column labels
df.to_numpy()

array([[-0.51647913,  1.14082071,  2.48291804,  1.18150522],
       [-0.16344192, -1.05521882, -2.08327874, -0.31200191],
       [ 2.16752024, -1.24603253, -0.18626395, -1.1390362 ],
       [ 1.55813133,  0.21169391, -1.46114925,  0.94569633],
       [-0.08541343,  2.94877751,  0.37317585, -0.13794203],
       [-0.26277551, -0.64423683,  0.56587452, -0.91406335]])

In [ ]:
#caution))
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [ ]:
df2.to_numpy()
#if the common data type is object, DataFrame.to_numpy() will
#require copying data

array([[1.0, Timestamp('2026-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2026-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2026-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2026-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [ ]:
#desrcibe() SHOws a quick statistic summary of your data
df.describe()

              a         b         c         d
count  6.000000  6.000000  6.000000  6.000000
mean   0.449590  0.225967 -0.051454 -0.062640
std    1.120976  1.601020  1.619764  0.950373
min   -0.516479 -1.246033 -2.083279 -1.139036
25%   -0.237942 -0.952473 -1.142428 -0.763548
50%   -0.124428 -0.216271  0.093456 -0.224972
75%    1.147245  0.908539  0.517700  0.674787
max    2.167520  2.948778  2.482918  1.181505

In [ ]:
#transporting your data, x,y AXIS INVERT!
df.T

   2026-01-01  2026-01-02  2026-01-03  2026-01-04  2026-01-05  2026-01-06
a   -0.516479   -0.163442    2.167520    1.558131   -0.085413   -0.262776
b    1.140821   -1.055219   -1.246033    0.211694    2.948778   -0.644237
c    2.482918   -2.083279   -0.186264   -1.461149    0.373176    0.565875
d    1.181505   -0.312002   -1.139036    0.945696   -0.137942   -0.914063

In [ ]:
#DataFrame.sort_index()
df.sort_index(axis=0,ascending=False)

                   a         b         c         d
2026-01-06 -0.262776 -0.644237  0.565875 -0.914063
2026-01-05 -0.085413  2.948778  0.373176 -0.137942
2026-01-04  1.558131  0.211694 -1.461149  0.945696
2026-01-03  2.167520 -1.246033 -0.186264 -1.139036
2026-01-02 -0.163442 -1.055219 -2.083279 -0.312002
2026-01-01 -0.516479  1.140821  2.482918  1.181505

In [ ]:
#DataFrame.sort_values() sort by values
df.sort_values(by="b")
#df2 2column="B"

                   a         b         c         d
2026-01-03  2.167520 -1.246033 -0.186264 -1.139036
2026-01-02 -0.163442 -1.055219 -2.083279 -0.312002
2026-01-06 -0.262776 -0.644237  0.565875 -0.914063
2026-01-04  1.558131  0.211694 -1.461149  0.945696
2026-01-01 -0.516479  1.140821  2.482918  1.181505
2026-01-05 -0.085413  2.948778  0.373176 -0.137942

In [ ]:
#selection : indexing and selecting data and multiindex/advanced index
#Getitem([]): for a DataFrame , passing a single label selects a column and yield a Series

df["a"]

2026-01-01   -0.516479
2026-01-02   -0.163442
2026-01-03    2.167520
2026-01-04    1.558131
2026-01-05   -0.085413
2026-01-06   -0.262776
Freq: D, Name: a, dtype: float64

In [ ]:
#if the label only contains letters,numbers,and underscores
#you can alternatively use the column name attribute
df.a

2026-01-01   -0.516479
2026-01-02   -0.163442
2026-01-03    2.167520
2026-01-04    1.558131
2026-01-05   -0.085413
2026-01-06   -0.262776
Freq: D, Name: a, dtype: float64

In [ ]:
#a list of column selects multiple columns, which can be useful for
#gettting a subset/rearranging
df[["b","a"]]

                   b         a
2026-01-01  1.140821 -0.516479
2026-01-02 -1.055219 -0.163442
2026-01-03 -1.246033  2.167520
2026-01-04  0.211694  1.558131
2026-01-05  2.948778 -0.085413
2026-01-06 -0.644237 -0.262776

In [ ]:
df[0:3]

                   a         b         c         d
2026-01-01 -0.516479  1.140821  2.482918  1.181505
2026-01-02 -0.163442 -1.055219 -2.083279 -0.312002
2026-01-03  2.167520 -1.246033 -0.186264 -1.139036

In [ ]:
df["20260101":"20260104"]

                   a         b         c         d
2026-01-01 -0.516479  1.140821  2.482918  1.181505
2026-01-02 -0.163442 -1.055219 -2.083279 -0.312002
2026-01-03  2.167520 -1.246033 -0.186264 -1.139036
2026-01-04  1.558131  0.211694 -1.461149  0.945696

In [ ]:
#selection by label
#select the label using DataFrame.loc() or DataFrame.at()
df.loc[dates[0]]
#selecting a row matching a label

a   -0.516479
b    1.140821
c    2.482918
d    1.181505
Name: 2026-01-01 00:00:00, dtype: float64

In [ ]:
#select all rows(:) with a select column labels
df.loc[:,["a","b"]]

                   a         b
2026-01-01 -0.516479  1.140821
2026-01-02 -0.163442 -1.055219
2026-01-03  2.167520 -1.246033
2026-01-04  1.558131  0.211694
2026-01-05 -0.085413  2.948778
2026-01-06 -0.262776 -0.644237

In [ ]:
#for label slicing, both endpoints are includeed
df.loc["20260101":"20260103",["a","b"]]

                   a         b
2026-01-01 -0.516479  1.140821
2026-01-02 -0.163442 -1.055219
2026-01-03  2.167520 -1.246033

In [ ]:
#selecting a single row and column label returns a scalar
df.loc[dates[0],"a"]

np.float64(-0.5164791349374369)

In [ ]:
#for getting fast access to a scalar(euiovalent to the prior method)
df.at[dates[0],"a"]

np.float64(-0.5164791349374369)

In [ ]:
#selection by position : see more in selection by position
#using DataFrame.iloc() or DataFrame.iat()
#select via the position of the passed integers
df.iloc[3] #행이나 열 선택, loc name, iloc inter sequence

a    1.558131
b    0.211694
c   -1.461149
d    0.945696
Name: 2026-01-04 00:00:00, dtype: float64

In [ ]:
#integer slice acts similar to numpy/python
df.iloc[3:5,0:2]

                   a         b
2026-01-04  1.558131  0.211694
2026-01-05 -0.085413  2.948778

In [ ]:
#list of integer position locations
df.iloc[[1,2,4],[0,2]]

                   a         c
2026-01-02 -0.163442 -2.083279
2026-01-03  2.167520 -0.186264
2026-01-05 -0.085413  0.373176

In [ ]:
#for slicing rows explicitly
df.iloc[:,1:3]

                   b         c
2026-01-01  1.140821  2.482918
2026-01-02 -1.055219 -2.083279
2026-01-03 -1.246033 -0.186264
2026-01-04  0.211694 -1.461149
2026-01-05  2.948778  0.373176
2026-01-06 -0.644237  0.565875

In [ ]:
#for gettting a value explicity
df.iloc[1,1]

np.float64(-1.0552188188230087)

In [ ]:
#for getting fast access to scalar(equivalent to the prior method)
df.iat[1,1]

np.float64(-1.0552188188230087)

In [ ]:
#boolean indexing
#select rows where df.a is greater than 0
df[df["a"]>0]

                   a         b         c         d
2026-01-03  2.167520 -1.246033 -0.186264 -1.139036
2026-01-04  1.558131  0.211694 -1.461149  0.945696

In [ ]:
#select values from a DataFrame where a boolean conditio is met
df[df>0]

                   a         b         c         d
2026-01-01       NaN  1.140821  2.482918  1.181505
2026-01-02       NaN       NaN       NaN       NaN
2026-01-03  2.167520       NaN       NaN       NaN
2026-01-04  1.558131  0.211694       NaN  0.945696
2026-01-05       NaN  2.948778  0.373176       NaN
2026-01-06       NaN       NaN  0.565875       NaN

In [ ]:
#using isin() method for filtering
df2=df.copy()

In [ ]:
df2["e"]=["one","one","two","three","four","three"]
df2

                   a         b         c         d      e
2026-01-01 -0.516479  1.140821  2.482918  1.181505    one
2026-01-02 -0.163442 -1.055219 -2.083279 -0.312002    one
2026-01-03  2.167520 -1.246033 -0.186264 -1.139036    two
2026-01-04  1.558131  0.211694 -1.461149  0.945696  three
2026-01-05 -0.085413  2.948778  0.373176 -0.137942   four
2026-01-06 -0.262776 -0.644237  0.565875 -0.914063  three

In [ ]:
df2[df2["e"].isin(["two","four"])]

                   a         b         c         d     e
2026-01-03  2.167520 -1.246033 -0.186264 -1.139036   two
2026-01-05 -0.085413  2.948778  0.373176 -0.137942  four

In [ ]:
#setting, setting a new column automatically aligns the data by the indexes
s1=pd.Series(
    [1,2,3,4,5,6],
    index=pd.date_range("20260102",periods=6)
)
s1

2026-01-02    1
2026-01-03    2
2026-01-04    3
2026-01-05    4
2026-01-06    5
2026-01-07    6
Freq: D, dtype: int64

In [ ]:
df["f"]=s1
#setting values by label

In [ ]:
df.at[dates[0],"a"]=0
#setting values by position

In [ ]:
df.loc[:,"d"]=np.array([5]*len(df))

In [ ]:
#result of the prior setting operations
df

                   a         b         c    d    f
2026-01-01  0.000000  1.140821  2.482918  5.0  NaN
2026-01-02 -0.163442 -1.055219 -2.083279  5.0  1.0
2026-01-03  2.167520 -1.246033 -0.186264  5.0  2.0
2026-01-04  1.558131  0.211694 -1.461149  5.0  3.0
2026-01-05 -0.085413  2.948778  0.373176  5.0  4.0
2026-01-06 -0.262776 -0.644237  0.565875  5.0  5.0

In [ ]:
#a where operation with setting
df2=df.copy()

In [ ]:
df2[df2>0]=-df2

In [ ]:
df2

                   a         b         c    d    f
2026-01-01  0.000000 -1.140821 -2.482918 -5.0  NaN
2026-01-02 -0.163442 -1.055219 -2.083279 -5.0 -1.0
2026-01-03 -2.167520 -1.246033 -0.186264 -5.0 -2.0
2026-01-04 -1.558131 -0.211694 -1.461149 -5.0 -3.0
2026-01-05 -0.085413 -2.948778 -0.373176 -5.0 -4.0
2026-01-06 -0.262776 -0.644237 -0.565875 -5.0 -5.0

In [ ]:
#missing data : np.nan represents missing data. it is
#by default not included in computation, see
# reindexing allow you to change/add/delete the index on a specifed axis
# this returns a copy of the data
df1=df.reindex(index=dates[0:4],columns=list(df.columns)+["e"])
#새로운 열 넣는법
df1.loc[dates[0]:dates[1],"e"]=1 #행렬위치 지정 값 넣는법
df1

                   a         b         c    d    f    e
2026-01-01  0.000000  1.140821  2.482918  5.0  NaN  1.0
2026-01-02 -0.163442 -1.055219 -2.083279  5.0  1.0  1.0
2026-01-03  2.167520 -1.246033 -0.186264  5.0  2.0  NaN
2026-01-04  1.558131  0.211694 -1.461149  5.0  3.0  NaN

In [ ]:
#DataFrame.dropna() drops any rows that have missing data
df1.dropna(how="any")

                   a         b         c    d    f    e
2026-01-02 -0.163442 -1.055219 -2.083279  5.0  1.0  1.0

In [ ]:
#DataFrame.fillna() fill missin data
df1.fillna(value=5)

                   a         b         c    d    f    e
2026-01-01  0.000000  1.140821  2.482918  5.0  5.0  1.0
2026-01-02 -0.163442 -1.055219 -2.083279  5.0  1.0  1.0
2026-01-03  2.167520 -1.246033 -0.186264  5.0  2.0  5.0
2026-01-04  1.558131  0.211694 -1.461149  5.0  3.0  5.0

In [ ]:
#isna() gets the boolean mask where values are nan:
pd.isna(df1)
#isna() vs dropna() 반대

                a      b      c      d      f      e
2026-01-01  False  False  False  False   True  False
2026-01-02  False  False  False  False  False  False
2026-01-03  False  False  False  False  False   True
2026-01-04  False  False  False  False  False   True

In [ ]:
#operation : binary ops
#stats : operation in general exclude missing data
#calculate the mena value fo each columns
df.mean()
#df.describe() 다모임(mean,std,25%..)

a    0.535670
b    0.225967
c   -0.051454
d    5.000000
f    3.000000
dtype: float64

In [ ]:
#calculate the mena value for each row
df.mean(axis=1)

2026-01-01    2.155935
2026-01-02    0.539612
2026-01-03    1.547045
2026-01-04    1.661735
2026-01-05    2.447308
2026-01-06    1.931772
Freq: D, dtype: float64

In [ ]:
#operating with another Series or DataFrame with a different index
# or column will align the result with the union of the inde
#or column labels. in addition, pandas automaticlally
#broadcasts along the spcified dimension and will fill
# unaligned labels with np.nan
s=pd.Series([1,3,5,np.nan,6,8],index=dates).shift(2)
s

2026-01-01    NaN
2026-01-02    NaN
2026-01-03    1.0
2026-01-04    3.0
2026-01-05    5.0
2026-01-06    NaN
Freq: D, dtype: float64

In [ ]:
#
df.sub(s,axis="index")

                   a         b         c    d    f
2026-01-01       NaN       NaN       NaN  NaN  NaN
2026-01-02       NaN       NaN       NaN  NaN  NaN
2026-01-03  1.167520 -2.246033 -1.186264  4.0  1.0
2026-01-04 -1.441869 -2.788306 -4.461149  2.0  0.0
2026-01-05 -5.085413 -2.051222 -4.626824  0.0 -1.0
2026-01-06       NaN       NaN       NaN  NaN  NaN

In [ ]:
#lambda 매개변수: 표현식
(lambda x,y:x+y)(10,20)

30

In [ ]:
#user defined functions
#DataFrame.agg() and DataFrame.transfrom() applies a user defined function
#that redueces or broadcasts its result respectively
df.agg(lambda x:np.mean(x)*5.6)
#agg(["mean","std","min","max"]) 인자를 원하는 것만 골라 반환 가능 , describe() 차이

#result 는 matrix or array? series?

a     2.999753
b     1.265417
c    -0.288142
d    28.000000
f    16.800000
dtype: float64

### dataframe vs series vs array

In [ ]:
#testing padndas.DataFrame.agg
# DataFrame.agg()
import pandas as pd
test=pd.DataFrame(
    [[1,2,3],[4,5,6],[7,8,9],[np.nan,np.nan,np.nan]],
    columns=["A","B","C"],
)
test.agg(["sum","min"])

        A     B     C
sum  12.0  15.0  18.0
min   1.0   2.0   3.0

In [ ]:
df.transform(lambda x :x*101.2)

                     a           b           c      d      f
2026-01-01    0.000000  115.451056  251.271305  506.0    NaN
2026-01-02  -16.540322 -106.788144 -210.827808  506.0  101.2
2026-01-03  219.353048 -126.098492  -18.849912  506.0  202.4
2026-01-04  157.682891   21.423424 -147.868305  506.0  303.6
2026-01-05   -8.643839  298.416284   37.765396  506.0  404.8
2026-01-06  -26.592882  -65.196767   57.266501  506.0  506.0

In [ ]:
#value counts
# see more
s=pd.Series(np.random.randint(0,7,size=10))
s

0    4
1    4
2    2
3    2
4    6
5    0
6    3
7    6
8    5
9    3
dtype: int64

In [ ]:
s.value_counts()

4    2
2    2
6    2
3    2
0    1
5    1
Name: count, dtype: int64

In [ ]:
#string methods
#series is eqipped with a set of string processing method in th str
# attribute that make it easy to operate on each element of the array
#as in the code snippet below, see more at ver

s=pd.Series(["A","B","C","Aaba","Baca",np.nan,"CABA","dog","cat"])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

In [ ]:
#merge > concat
# which is facilities for easily combining together Series and DataFrame
#
df=pd.DataFrame(np.random.randn(10,4))
df

          0         1         2         3
0 -0.015909 -0.777873  0.527982  0.368193
1 -1.219263  1.105157  1.223174  0.514225
2 -0.156937  1.785515  0.408901 -0.278948
3  0.508624 -0.495612 -0.505630 -0.862195
4 -0.951141 -0.488545  2.380230 -2.805720
5  1.610067  1.354823 -0.968211 -0.829880
6 -1.486818  0.406037  0.513823  1.045085
7  0.890389 -0.998927 -0.365749 -0.731676
8  0.522783 -0.973837 -0.037381 -0.269950
9 -1.786466 -1.855228 -1.645884  0.410707

## concat??

In [ ]:
#break it into pieces
pieces=[df[:3],df[3:7],df[7:]]
pd.concat(pieces)

          0         1         2         3
0 -0.015909 -0.777873  0.527982  0.368193
1 -1.219263  1.105157  1.223174  0.514225
2 -0.156937  1.785515  0.408901 -0.278948
3  0.508624 -0.495612 -0.505630 -0.862195
4 -0.951141 -0.488545  2.380230 -2.805720
5  1.610067  1.354823 -0.968211 -0.829880
6 -1.486818  0.406037  0.513823  1.045085
7  0.890389 -0.998927 -0.365749 -0.731676
8  0.522783 -0.973837 -0.037381 -0.269950
9 -1.786466 -1.855228 -1.645884  0.410707

In [ ]:
#break it into pieces
pieces02=[df[,0],df[,1:3],df[,3]]
pd.concat(pieces02)

SyntaxError: invalid syntax (328621707.py, line 2)

In [ ]:
#join ; merge() enables SQL join types along sepcific columns
left=pd.DataFrame({"key":["foo","foo"],"lval":[1,2]})
right=pd.DataFrame({"key":["foo","foo"],"rval":[4,5]})

left

   key  lval
0  foo     1
1  foo     2

In [ ]:
right

   key  rval
0  foo     4
1  foo     5

In [ ]:
pd.merge(left,right,on="key") #??
#merge() enable sql style join types along specific column

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [ ]:
#merge() on unique keys
left=pd.DataFrame({"key":["foo","foo"],"lval":[1,2]})
right=pd.DataFrame({"key":["foo","foo"],"rval":[4,5]})

left

   key  lval
0  foo     1
1  foo     2

In [ ]:
right

   key  rval
0  foo     4
1  foo     5

In [ ]:
pd.merge(left,right,on="key")
#merge() on unique keys # equivalent prior one??

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [ ]:
#grouping
#by group by we are referring to a process involving one or more of  the
#following steps, 1.splitting the data into groups based on some criteria
#2.applying : a function to each group indenpendently
#3.combining the result into a data structure
import pandas as pd
import numpy as np

df=pd.DataFrame({
    "a":["foo","bar","foo","bar","foo","bar","foo","foo"],
    "b":["one","one","two","three","two","two","one","three"],
    "c":np.random.randn(8),
    "d":np.random.randn(8),
})
df

     a      b         c         d
0  foo    one -0.184310  0.048626
1  bar    one  0.187634  1.017651
2  foo    two  0.295979  0.958320
3  bar  three  1.012619  0.020346
4  foo    two  0.592146  0.650691
5  bar    two  0.818790 -1.151580
6  foo    one -0.050104  0.822066
7  foo  three -0.765293  0.199503

In [ ]:
#group by a column label, sleelcing column label , and thenm applying the DataFrame
#DataFrameGroupby.sum()

df.groupby("a")[['c','d']].sum()

            c         d
a
bar  2.019044 -0.113583
foo -0.111582  2.679207

In [ ]:
#grouping by mupliple columns label forms multiindex
df.groupby(["a","b"]).sum()

                  c         d
a   b
bar one    0.187634  1.017651
    three  1.012619  0.020346
    two    0.818790 -1.151580
foo one   -0.234415  0.870692
    three -0.765293  0.199503
    two    0.888125  1.609011

In [ ]:
#pd.pivot_table() : create a spreadsheet-style pivot table as a DataFrame
#
import pandas as pd
import numpy as np
pivot_df=pd.DataFrame(
    {
        "a":["foo","foo","foo","foo","foo","bar","bar","bar","bar"],
        "b":["one","one","one","two","two","one","one","two","two"],
        "c":["small","large","large","small","small","large","smnall","small","large"],
        "d":[1,2,2,3,3,4,5,6,7],
        "e":[2,4,5,5,6,6,8,9,9],

    }
)
pivot_df

     a    b       c  d  e
0  foo  one   small  1  2
1  foo  one   large  2  4
2  foo  one   large  2  5
3  foo  two   small  3  5
4  foo  two   small  3  6
5  bar  one   large  4  6
6  bar  one  smnall  5  8
7  bar  two   small  6  9
8  bar  two   large  7  9

In [ ]:
#the first example aggregates values by talking the sum
# DataFrame.pivot() ; pivot without aggregation that can handle non-numeric data
table=pd.pivot_table(
    pivot_df,values="d",index=["a","b"],columns=["c"],aggfunc="sum"
)
table
# 설명 : 멀티 인티인텍스 index["a","b"]

c        large  small  smnall
a   b
bar one    4.0    NaN     5.0
    two    7.0    6.0     NaN
foo one    4.0    1.0     NaN
    two    NaN    6.0     NaN

In [ ]:
table=pd.pivot_table(
  pivot_df,values="d",index=["a","b"],columns=["c"],aggfunc="sum",fill_value=0
)
table

c        large  small  smnall
a   b
bar one      4      0       5
    two      7      6       0
foo one      4      1       0
    two      0      6       0

In [ ]:
table=pd.pivot_table(
    pivot_df, values=["d","e"],index=["a","c"],aggfunc={"d":"mean","e":"mean"}
)
table

                   d         e
a   c
bar large   5.500000  7.500000
    small   6.000000  9.000000
    smnall  5.000000  8.000000
foo large   2.000000  4.500000
    small   2.333333  4.333333

In [ ]:
table=pd.pivot_table(
    pivot_df,values=["d","e"],index=["a","c"],aggfunc={"d":"mean","e":["min","max","mean"]}
)
table

                   d   e
                mean max      mean min
a   c
bar large   5.500000   9  7.500000   6
    small   6.000000   9  9.000000   9
    smnall  5.000000   8  8.000000   8
foo large   2.000000   5  4.500000   4
    small   2.333333   6  4.333333   2

In [ ]:
#time series: for performing resampling operations during frequency conversion
# e.g) converting secondly data into 5-minutely data.
#This is exrememly common in, but nit limited to financial applications. see the time Series section
import pandas as pd
import numpy as np
rng= pd.date_range("1/1/2012",periods=100,freq="s")
ts=pd.Series(np.random.randint(0,500,len(rng)),index=rng)

ts.resample("5min").sum()

2012-01-01    23910
Freq: 5min, dtype: int64

In [ ]:
#Series.tz_localize() : localize a time series to a time zone
rng=pd.date_range("3/6/2012 00:02", periods=5,freq="d")
ts=pd.Series(np.random.randn(len(rng)),rng)

ts

2012-03-06 00:02:00    1.045019
2012-03-07 00:02:00    0.015225
2012-03-08 00:02:00   -0.439037
2012-03-09 00:02:00   -0.483606
2012-03-10 00:02:00   -0.214912
Freq: D, dtype: float64

In [ ]:
ts_utc=ts.tz_localize("UTC")
ts_utc

2012-03-06 00:02:00+00:00    1.045019
2012-03-07 00:02:00+00:00    0.015225
2012-03-08 00:02:00+00:00   -0.439037
2012-03-09 00:02:00+00:00   -0.483606
2012-03-10 00:02:00+00:00   -0.214912
Freq: D, dtype: float64

In [ ]:
#Series.tz_convert() : convert a timezones aware time series to another time zone
#
ts_utc.tz_convert("us/eastern")

2012-03-05 19:02:00-05:00    1.045019
2012-03-06 19:02:00-05:00    0.015225
2012-03-07 19:02:00-05:00   -0.439037
2012-03-08 19:02:00-05:00   -0.483606
2012-03-09 19:02:00-05:00   -0.214912
Freq: D, dtype: float64

In [ ]:
#addding a non-fixed duration(BusinessDay) to a time series
rng

DatetimeIndex(['2012-03-06 00:02:00', '2012-03-07 00:02:00',
               '2012-03-08 00:02:00', '2012-03-09 00:02:00',
               '2012-03-10 00:02:00'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
rng+pd.offsets.BusinessDay(5)

DatetimeIndex(['2012-03-13 00:02:00', '2012-03-14 00:02:00',
               '2012-03-15 00:02:00', '2012-03-16 00:02:00',
               '2012-03-16 00:02:00'],
              dtype='datetime64[ns]', freq=None)

In [ ]:
#Categoricals
#pandas can include categorical data in a DataFrame. For full docs, see the categorical
#introductuiob and the APIdocumentation

df=pd.DataFrame(
    {"id":[1,2,3,4,5,6],"raw_grade":["a","b","b","a","a","e"]}
)

In [ ]:
#converting the raw grades to a categorical data type
df["grade"]=df["raw_grade"].astype("category")
df["grade"]

0    a
1    b
2    b
3    a
4    a
5    e
Name: grade, dtype: category
Categories (3, object): ['a', 'b', 'e']

In [ ]:
#rename the categories to more meaningful names
new_categories=["very good","good","very bad"]
df["grade"]=df["grade"].cat.rename_categories(new_categories)
df["grade"]

0    very good
1         good
2         good
3    very good
4    very good
5     very bad
Name: grade, dtype: category
Categories (3, object): ['very good', 'good', 'very bad']

In [ ]:
#reorder the categories and simultaneously add the missing categories(method under Series.cat())
#return a new Series bt default()
df["grade"]=df["grade"].cat.set_categories(
    ["very bad","bad","medium","good","very good"]
)
df["grade"]

0    very good
1         good
2         good
3    very good
4    very good
5     very bad
Name: grade, dtype: category
Categories (5, object): ['very bad', 'bad', 'medium', 'good', 'very good']

In [ ]:
#sorting si per order in the categories, not lexical order
df.sort_values(by="grade")

   id raw_grade      grade
5   6         e   very bad
1   2         b       good
2   3         b       good
0   1         a  very good
3   4         a  very good
4   5         a  very good